'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bomb_Diffuser.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gpic9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gpic9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1202021202021
        '''1011101011111
        '''1312021202021
        '''1010111111101
        '''1212021202031
        '''1011101011101
        '''1212020212021
        '''1011111111101
        '''1202021202121
        '''1011101011101
        '''1202120212021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze1() As String
            Get
                Return ResourceManager.GetString("Maze1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1202021202021
        '''1110111010111
        '''1202120213021
        '''1011101111101
        '''1212021202021
        '''1010111011101
        '''1203120212121
        '''1011101110101
        '''1212121202121
        '''1010101011101
        '''1212021202021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze2() As String
            Get
                Return ResourceManager.GetString("Maze2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1202021212021
        '''1011101010101
        '''1212121202121
        '''1110101111101
        '''1202121202121
        '''1010101010101
        '''1212121312131
        '''1010101010101
        '''1212021212121
        '''1011111010101
        '''1202020212021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze3() As String
            Get
                Return ResourceManager.GetString("Maze3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1302120202021
        '''1010111111101
        '''1212120202021
        '''1010101111101
        '''1212021202121
        '''1011111011101
        '''1312020202021
        '''1011111111101
        '''1202020202121
        '''1011111110101
        '''1202021202121
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze4() As String
            Get
                Return ResourceManager.GetString("Maze4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1202020202021
        '''1111111110101
        '''1202020202121
        '''1011111011111
        '''1202120213021
        '''1010111110101
        '''1212020212121
        '''1011111011101
        '''1212020202121
        '''1010111111101
        '''1212020302021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze5() As String
            Get
                Return ResourceManager.GetString("Maze5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1212021203021
        '''1010101110101
        '''1212121202121
        '''1010101011101
        '''1202121212021
        '''1011111010111
        '''1202120212121
        '''1110101010101
        '''1202131212021
        '''1011111011101
        '''1202020212021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze6() As String
            Get
                Return ResourceManager.GetString("Maze6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1203020212021
        '''1011111010101
        '''1212021202121
        '''1010111111101
        '''1202120212021
        '''1111101110111
        '''1202120202121
        '''1010101111101
        '''1212120202121
        '''1011111110101
        '''1203020202021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze7() As String
            Get
                Return ResourceManager.GetString("Maze7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1212020312021
        '''1010111010101
        '''1202021202121
        '''1011111111101
        '''1212020202121
        '''1010111110101
        '''1212031202021
        '''1011101111111
        '''1212120202021
        '''1010111111111
        '''1202020202021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze8() As String
            Get
                Return ResourceManager.GetString("Maze8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111
        '''1212020202021
        '''1010111110101
        '''1212130212121
        '''1010101110101
        '''1202021202121
        '''1011111011101
        '''1212120212021
        '''1010101111101
        '''1312121202121
        '''1010101010111
        '''1202120212021
        '''1111111111111.
        '''</summary>
        Friend ReadOnly Property Maze9() As String
            Get
                Return ResourceManager.GetString("Maze9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
